"""empty message

Revision ID: 259afa33cad0
Revises: 58377cfff7b0
Create Date: 2020-07-19 20:28:45.616795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259afa33cad0'
down_revision = '58377cfff7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###
