"""empty message

Revision ID: 58377cfff7b0
Revises: 9f4ce0dccc47
Create Date: 2020-07-19 20:03:05.562594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58377cfff7b0'
down_revision = '9f4ce0dccc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'image_link')
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
